title: DocuSnap
description: Your AI-powered Personal Document Assistant
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# Custom app store URLs
app_store_url: "https://apps.apple.com/docusnap"
google_play_url: "https://play.google.com/store/apps/details?id=com.deepsleep.docusnap"

# Favicon
favicon: "/assets/images/docusnap-icon.png"